apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/keithgairnvm/jxtest:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/keithgairnvm/jxtest:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: jxtest
        chartPath: charts/jxtest
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/keithgairnvm/jxtest'
          image.tag: '{{.DIGEST_HEX}}'
